headersOrigin = "config"
redirectsOrigin = "config"

[functions]

  [functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

  [plugins.inputs]

[build]
publish = "/Users/aamirfaiz/Downloads/maps-driving/development/project2/maps-driving-next/out"
publishOrigin = "config"
command = "npm run build"
commandOrigin = "config"

  [build.environment]
  NEXT_DISABLE_ESLINT = "1"
  NEXT_USE_NETLIFY_EDGE = "1"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_BASE_PATH = ""

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[headers]]
for = "/*"

  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/_next/static/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/static/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/images/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"

[[redirects]]
from = "/_next/static/*"
to = "/_next/static/:splat"
status = 200
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/images/*"
to = "/images/:splat"
status = 200
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/mapquest-mileage"
to = "/mapquest-mileage.html"
status = 200
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]